const DEFAULT_TIMEOUT = 10000;
const LONG_TIMEOUT = 30000;
const SHORT_TIMEOUT = 3000;
const ANIMATION_TIMEOUT = 2000;

module.exports = { DEFAULT_TIMEOUT, LONG_TIMEOUT, SHORT_TIMEOUT, ANIMATION_TIMEOUT };
